### ISSUE TITLE
Docker 24.0 is out with deprecations and API version bump

### ISSUE THREAD

**Issue by ieugen** [lispyclouds/contajners#19]
https://docs.docker.com/engine/release-notes/24.0/

**Comment by lispyclouds** [comment]
PR welcome! This is what I do:
- Add the new version here: https://github.com/lispyclouds/contajners/blob/main/fetch_api/main.clj#L16
- From the root of the repo run `clojure -J--enable-preview -X:fetch-api` (needs JDK 19+)
- That should produce a new edn file in the [docker api list](https://github.com/lispyclouds/contajners/tree/main/resources/contajners/docker)
- Make sure I'm able to use it locally and push it!

Hope this helps!

**Comment by ieugen** [comment]
Seems API is still at 1.42 and should be supported.
 Sorry for the commotion. 
There are some API updates on podman side - I think they changed some keys / names. 
Might break some things?! - not sure 
Made a PR for that.

**Comment by lispyclouds** [comment]
No worries! Also re: Breaking changes, we cant really do much, contajners is just a thin interface; cant protect against that. 😃

**Comment by ieugen** [comment]
> cant protect against that.
Sure. Maybe a mention / warning is in order.

**Comment by ieugen** [comment]
Closing this as I don't think we need to do anything.
