### ISSUE TITLE
Prepare for upcoming API 1.44 - moby V25 

### ISSUE THREAD

**Issue by ieugen** [lispyclouds/contajners#24]
Moby 25 is in beta - should release in the next moth or so: https://github.com/moby/moby/releases/tag/v25.0.0-beta.3

> API v1.44 (Moby v25) and API v1.45 (Moby v26)

**Comment by ieugen** [comment]
It's alive with some API changes: https://docs.docker.com/engine/release-notes/25.0/

**Comment by lispyclouds** [comment]
Released in 1.0.3
