### ISSUE TITLE
Add ContainerArchive operation 

### ISSUE THREAD

**Issue by rafaeldelboni** [lispyclouds/contajners#26]
You listed container archive as an experimental Api [here](https://github.com/lispyclouds/contajners/blob/main/doc/002-general-guidelines.md#accessing-undocumentedexperimental-apis), but now in the recent versions I think it is part of the official Api:
https://docs.docker.com/engine/api/v1.44/#tag/Container/operation/ContainerArchive

**Comment by lispyclouds** [comment]
this is for [checkpoints](https://docs.docker.com/reference/cli/docker/checkpoint/) which i believe is still experimental. the one you linked to is the archiving one which should've been there for a while.

**Comment by lispyclouds** [comment]
I suppose the way the doc is written makes it a bit confusing i agree. Making that clearer now.

**Comment by lispyclouds** [comment]
does [this](https://github.com/lispyclouds/contajners/commit/3780adf68000c7cd0fceb05584cf5f235bde78ee) make it better?

**Comment by rafaeldelboni** [comment]
Yes, thanks, is there an example of archive using the container operation? 

If not,would nice to add as well, I will try use this afternoon and I can send an pr if you like só.

**Comment by lispyclouds** [comment]
I don't believe there is an example of it in the docs and PRs are most welcome! Here is an [example](https://github.com/bob-cd/bob/blob/main/runner/src/runner/engine.clj#L286-L298) in a codebase which uses Podman but should very similar. Can use `ContainerArchive` instead of `ContainerArchiveLibpod` I think.

**Comment by rafaeldelboni** [comment]
Something like this for writing files to an container right?
```clojure
(c/invoke containers-docker
          {:op     :PutContainerArchive
           :params {:id container-name
                    :path "/usr/src/app"}
           :data (-> "src.tar.gz"
                     io/file
                     io/input-stream)
           :as     :stream
           :throw-exceptions true
           :throw-entire-message true})
```
