### ISSUE TITLE
Provide compatibility with babashka

### ISSUE THREAD

**Issue by ieugen** [lispyclouds/contajners#3]
It would be very nice to have compatibility with babashka and be able to script interactions with podman and docker.

Right now, the difficult part is docker http over unix sockets. 
There is https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8275838 to the jdk web client work over unix domain sockets but it might take some time. 

Until then we might be able to use babashka-curl library as an http alternative. 

This was discussed on slack https://clojurians-log.clojureverse.org/babashka-sci-dev/2021-10-23 .

**Comment by ieugen** [comment]
I added a PR to call curl and get images.
I println the :body since contajners seems to do it's own parsing but bb curl returns a parsed response.

**Comment by imdahmd** [comment]
@ieugen I'm unable to see how `curl/request` can be used to pass a query-param and also specify the method. May be we will need to map `:method` to the corresponding call like `curl/get`, `curl/post` etc.
The code you pushed doesn't seem to work yet with the examples under the comment section of core.clj

**Comment by lispyclouds** [comment]
@ieugen @imdahmd we can maybe use the sort of _undocumented_ `babashka.curl/request` for this: https://github.com/babashka/babashka.curl/blob/master/src/babashka/curl.clj#L230 😄

**Comment by lispyclouds** [comment]
https://github.com/babashka/babashka.curl#url-construction

**Comment by imdahmd** [comment]
Yeah, i stand corrected. I had to go into the code to discover that. Excuse my naivety 😄 
I have just pushed a commit that maps the req more appropriately to the format accepted by bb/curl

**Comment by lispyclouds** [comment]
Awesome! Yeah lets get this to work with as many experiments as possible and have an overall review when its in a shape; y'all can feel free to choose the implementation details 😄

**Comment by imdahmd** [comment]
@lispyclouds Experimenting is the only way i can think of right now haha.
Atleast all the verification "tests" from you `comment` section are working with bb at this point 🥳

**Comment by lispyclouds** [comment]
Implemented by https://github.com/lispyclouds/contajners/commit/069646cbba87db812c4b7a6e636395fe622fc353
