### ISSUE TITLE
How to send parameters multiple times?

### ISSUE THREAD

**Issue by leahneukirchen** [lispyclouds/contajners#8]
The Podman API requires sending parameters multiple times for some calls, e.g
https://docs.podman.io/en/latest/_static/api.html#operation/ContainersStatsAllLibpod
or
https://docs.podman.io/en/latest/_static/api.html#operation/ImageCommitLibpod

(Listed as "arrays of strings".)

I found no way to make such requests, rt/request seems to work with `{:query-params [["name" "val1"] ["name" "val2"]]}` but perhaps more by accident. It would be good to support passing vectors of strings directly in `:params`.

**Comment by lispyclouds** [comment]
Ah yes, i will have a look into it soon and think of a way. Thanks for this @leahneukirchen 😄

**Comment by lispyclouds** [comment]
Raised https://github.com/into-docker/unixsocket-http/issues/17 lets see if we can have a proper fix there then we can propagate it back here.

**Comment by lispyclouds** [comment]
@leahneukirchen the Podman APi doesnt take `containers` or `changes` as the key for the query params as mentioned in the docs right? It wants `name` or `id` as keys for `ContainersStatsAllLibpod` and `CMD` etc as keys for `ImageCommitLibpod` as I understand right?

**Comment by lispyclouds** [comment]
what I'm confused about is should the request have `?changes=CMD%3Dfoo&changes=ENTRYPOINT%3Dbar` or `?CMD=foo&changes=ENTRYPOINT=bar`?

**Comment by leahneukirchen** [comment]
no, the key is `changes=`, so `changes=CMD%20foo`(!!!), `changes=ENTRYPOINT%20bar`

**Comment by lispyclouds** [comment]
Right, but for `ContainersStatsAllLibpod` youre sending `name=foo&name=bar` right?

**Comment by leahneukirchen** [comment]
Not sure how you come up with `name`, it says:

`containers | Array of strings names or IDs of containers`

So just `containers=foo&containers=bar`, the distinction between name and id is syntactical.

**Comment by lispyclouds** [comment]
Ahh i got confused by the example you mentioned: `{:query-params [["name" "val1"] ["name" "val2"]]}` and the docs which also says `name`. Sorry for that 😅 got it now!

**Comment by lispyclouds** [comment]
Could you try out https://github.com/lispyclouds/contajners/commit/1c19c194a9386c0dceeeae851fa8cdeb57590925 ? Should work for the JVM runtime. I in the meantime would need to add support for the same thing in https://github.com/babashka/babashka.curl for the bb runtime.

**Comment by lispyclouds** [comment]
Supported on bb too now.

**Comment by lispyclouds** [comment]
Released in `0.0.5`
