### ISSUE TITLE
Docker ImageLoad not working

### ISSUE THREAD

**Issue by fmardini** [lispyclouds/contajners#9]
Hi,

The API call to load a docker image (as generated by `docker save img:v1 | gzip > img.tar.gz`) is failing
I was getting a header error. I even tried to change the :api to allow adding headers, but still no luck

```
(require '[contajners.core :as c])
(def images-docker (c/client {:engine :docker :category :images :version "v1.41" :conn {:uri "unix:///var/run/docker.sock"}}))

(c/invoke images-docker {:op :ImageLoad :data (slurp "img.tar.gz") :throw-exceptions true})
;; {:errorDetail {:message "Error processing tar file(exit status 1): archive/tar: invalid tar header"}, :error "Error processing tar file(exit status 1): archive/tar: invalid tar header"}

(def images-docker2 (update-in images-docker [:api :ImageLoad :params] conj {:name "Content-type" :in :header}))
(def params {:Content-type "application/xtar"})
(c/invoke images-docker2 {:op :ImageLoad :data (slurp "img.tar.gz") :params params :throw-exceptions true})
;; {:errorDetail {:message "Error processing tar file(exit status 1): archive/tar: invalid tar header"}, :error "Error processing tar file(exit status 1): archive/tar: invalid tar header"}
```

Is this operation supported?

Many thanks,
Fouad

**Comment by lispyclouds** [comment]
Hey @fmardini!

Thanks for raising this, I have not tried this one but have a suspicion that docker can only handle tar images not tar.gz. Could you try once without the gzip, just that tar?

**Comment by lispyclouds** [comment]
Also you should be able to pass the inputstream of the file instead of reading it all into a string with slurp. try passing `(clojure.java.io/input-stream "image.tar")` instead of the slurp. should be more efficient.

**Comment by lispyclouds** [comment]
Also now that I think of it, the slurping of the data could be encoding it in a wrong way and passing it as raw bytes should be better. Try the gzip too once if you can? 😅 but both gzip and just the tar sent as an `input-stream` not a string.

**Comment by fmardini** [comment]
Thank you! Indeed `input-stream` did the trick

reading the `invoke` docs I don't know I thought it only took a string or a map

**Comment by lispyclouds** [comment]
Awesome! In general whenever you see that a parameter is takes a file or a binary input from the docker docs, you should be able to use an input stream there. I will add this to the docs! 😄

**Comment by fmardini** [comment]
Appreciate it! Thanks again
